### PR TITLE
adds a new attribute Component for tagging/grouping tests with servic…

### PR DESCRIPTION
**Pull request by ZahidMKhan**
adding a new tag
[Component]

### CODE REVIEW

**Review by brendanconnolly — APPROVED** [review]
thanks for contributing! I'll see about getting the nuget package updated.

**Comment by ZahidMKhan** [comment]
Thanks! I will look out for the updated package, or if you can post it here that'd be a nice alert too.

**Comment by ZahidMKhan** [comment]
@brendanconnolly any chance for the nuget update to happen soon? Would really like to see it in action in my own project :)

**Comment by baynezy** [comment]
@ZahidMKhan https://github.com/baynezy/Xunit.OpenCategories/blob/develop/CHANGELOG.md#1104---2024-09-22

**Comment by ZahidMKhan** [comment]
@baynezy really appreciate it.
@brendanconnolly any hopes for the nuget update? or do you recommend switching to baynezy's maintained project?

**Comment by brendanconnolly** [comment]
@ZahidMKhan package available on nuget in v3.0.

**Pull request merged**
