### PR TITLE
 new Attributes: Documentation, Exploratory, KownBug, WorkItem

### PR DESCRIPTION
**Pull request by jasonwurzel**
I created some new Attributes we need for our daily work. I'd be happy if you'd agree to merge them.

### CODE REVIEW

**Comment by brendanconnolly** [comment]
thanks for contributing!

**Comment by jasonwurzel** [comment]
glad to help :-) one more thing: could you update the nuget package?

**Comment by jasonwurzel** [comment]
(don't know if you got my last reply, so just mentioning you here @brendanconnolly : please see my comment above about the nuget package, thanks!)

**Comment by brendanconnolly** [comment]
I saw, but there was actually an issue with the latest pull request that was causing tests to fail that I uncovered while migrating the xunit.categories project to use netstandard1.1. Now the assembly follows the standard that xunit is using. Nuget package is now updated.

the change is below
-			var workItemId = traitAttribute.GetNamedArgument<string>("WorkItemIdId");
+			var workItemId = traitAttribute.GetNamedArgument<string>("WorkItemId");

**Comment by jasonwurzel** [comment]
oh I'm sorry about that...
Thank you very much for updating!

**Pull request merged**
